name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - staging
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Build Docker Images
        run: docker-compose build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/staging'

    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_KEY }}" | tr -d '\r' > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H 147.79.107.45 >> ~/.ssh/known_hosts

      - name: Debug SSH
        run: |
          ssh -v root@147.79.107.45 "echo 'SSH connected!'"

      - name: Deploy to Staging
        if: github.ref == 'refs/heads/staging'
        run: |
          ssh -t root@147.79.107.45 "
            cd /staging || mkdir -p /staging && cd /staging &&
            git pull origin staging || git clone https://github.com/pauloh-andrade/friendfin.git . &&
            docker-compose down && docker-compose up -d app-staging"

      - name: Deploy to Production
        if: github.ref == 'refs/heads/main'
        run: |
          ssh -t root@147.79.107.45 "
            cd /production || mkdir -p /production && cd /production &&
            git pull origin main || git clone https://github.com/pauloh-andrade/friendfin.git . &&
            docker-compose down && docker-compose up -d app-production"
