name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build Docker Images
        run: docker-compose build

      - name: Run Tests
        run: docker run --rm firenfin:latest mvn test

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy to Staging
        run: |
          ssh -o StrictHostKeyChecking=no user@your-staging-server "cd /path/to/staging && docker-compose down && docker-compose up -d"

      - name: Deploy to Production
        run: |
          ssh -o StrictHostKeyChecking=no user@your-production-server "cd /path/to/production && docker-compose down && docker-compose up -d"
